apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-mssql
spec:
  parentRefs:
  - name: agentgateway
  rules:
   - matches:
       - path:
           type: PathPrefix
           value: /mcp/mcp-mssql
     backendRefs:
       - name: mcp-mssql-backend
         group: agentgateway.dev
         kind: AgentgatewayBackend
