apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: mcp-ui
spec:
  parentRefs:
  - name: agentgateway
    group: gateway.networking.k8s.io
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /ui
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: /
    backendRefs:
    - name: mcp-ui-service
      port: 3000
  - matches:
    - path:
        type: PathPrefix
        value: /auth
    backendRefs:
    - name: mcp-ui-service
      port: 3000