apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mcpHubspot.deployment.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-hubspot
  template:
    metadata:
      labels:
        app: mcp-hubspot
    spec:
      containers:
        - name: mcp-hubspot
          image: "{{ .Values.mcpHubspot.deployment.image.repository }}:{{ .Values.mcpHubspot.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.mcpHubspot.deployment.image.pullPolicy }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mcpHubspot.service.name }}
  labels:
    app: mcp-hubspot
spec:
  selector:
    app: mcp-hubspot
  ports:
    - port: {{ .Values.mcpHubspot.service.port }}
      targetPort: {{ .Values.mcpHubspot.service.targetPort }}
      appProtocol: {{ .Values.mcpHubspot.service.appProtocol }}
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: {{ .Values.mcpHubspot.backend.name }}
spec:
  mcp:
    targets:
      - name: {{ .Values.mcpHubspot.backend.targetName }}
        static:
          host: {{ tpl .Values.mcpHubspot.backend.host . | quote }}
          port: {{ .Values.mcpHubspot.service.port }}
          protocol: {{ .Values.mcpHubspot.backend.protocol }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.mcpHubspot.httpRoute.name }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp/mcp-hubspot
      backendRefs:
        - name: {{ .Values.mcpHubspot.backend.name }}
          group: agentgateway.dev
          kind: AgentgatewayBackend