apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mcpMssql.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mcp-mssql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mcpMssql.deployment.replicas }}
  selector:
    matchLabels:
      {{- include "mcp-mssql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mcp-mssql.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mcp-mssql
          image: {{ include "bmg-agent-gateway.mcpMssql.image.repository" . }}:{{ include "bmg-agent-gateway.mcpMssql.image.tag" . }}
          imagePullPolicy: {{ include "bmg-agent-gateway.mcpMssql.image.pullPolicy" . }}
          env:
            - name: MSSQL_SERVER
              value: {{ include "bmg-agent-gateway.mcpMssql.mssqlServer" . | quote }}
            - name: MSSQL_DATABASE
              value: {{ include "bmg-agent-gateway.mcpMssql.mssqlDatabase" . | quote }}
            - name: MSSQL_PORT
              value: {{ include "bmg-agent-gateway.mcpMssql.mssqlPort" . | quote }}
            - name: MSSQL_USER
              value: {{ include "bmg-agent-gateway.mcpMssql.mssqlUser" . | quote }}
            - name: MSSQL_PASSWORD
              value: {{ include "bmg-agent-gateway.mcpMssql.mssqlPassword" . | quote }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mcpMssql.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mcp-mssql.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mcp-mssql.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.mcpMssql.service.port }}
      targetPort: {{ .Values.mcpMssql.service.targetPort }}
      appProtocol: {{ .Values.mcpMssql.service.appProtocol }}
---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayBackend
metadata:
  name: {{ .Values.mcpMssql.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  mcp:
    targets:
      - name: {{ .Values.mcpMssql.backend.targetName }}
        static:
          host: {{ tpl .Values.mcpMssql.backend.host . | quote }}
          port: {{ .Values.mcpMssql.service.port }}
          protocol: {{ .Values.mcpMssql.backend.protocol }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.mcpMssql.httpRoute.name }}
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
    - name: {{ include "bmg-agent-gateway.gateway.name" . }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /mcp/mcp-mssql
      backendRefs:
        - name: {{ .Values.mcpMssql.backend.name }}
          group: agentgateway.dev
          kind: AgentgatewayBackend