apiVersion: v2
name: agentgateway-helm
description: Umbrella chart for AgentGateway deployment
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: bmg-agent
  version: "0.1.0"
  repository: "file://./bmg-agent"
- name: bmg-ui
  version: "0.1.0"
  repository: "file://./bmg-ui"
- name: mcp-hubspot
  version: "0.1.0"
  repository: "file://./mcp-hubspot"
- name: mcp-mssql
  version: "0.1.0"
  repository: "file://./mcp-mssql"
- name: mcpagentcontrolplane
  version: "0.1.0"
  repository: "file://./mcpagentcontrolplane"