apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: {{ .Values.policy.name }}
  namespace: {{ .Values.namespace }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .Values.gateway.name }}
  traffic:
    jwtAuthentication:
      mode: Strict
      providers:
      - issuer: {{ .Values.policy.issuer }}
        audiences: {{ .Values.policy.audiences }}
        jwks:
          remote:
            cacheDuration: 5m
            backendRef:
              group: ""
              kind: Service
              name: {{ .Values.service.name }}
              port: 443
            jwksPath: {{ .Values.policy.jwksPath }}