apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: azure-mcp-authn-policy
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: agentgateway
  traffic:
    jwtAuthentication:
      mode: Strict
      providers:
      - issuer: https://sts.windows.net/a842fba6-0f79-40e7-98f3-21cb1a8c3365/
        audiences:
        - api://11ddc0cd-e6fc-48b6-8832-de61800fb41e
        jwks:
          remote:
            cacheDuration: 5m
            backendRef:
              group: ""
              kind: Service
              name: azure-ad-jwks
              port: 443
            jwksPath: /a842fba6-0f79-40e7-98f3-21cb1a8c3365/discovery/keys
---
apiVersion: v1
kind: Service
metadata:
  name: azure-ad-jwks
spec:
  type: ExternalName
  externalName: login.microsoftonline.com
