apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: azure-mcp-authn-policy
  
spec:
  targetRefs:
    - name: agentgateway
      kind: Gateway
      group: gateway.networking.k8s.io
  traffic:
    jwtAuthentication:
      mode: Strict
      providers:
        - issuer: https://sts.windows.net/6ba231bb-ad9e-41b9-b23d-674c80196bbd/
          jwks:
            remote:
              uri: https://login.microsoftonline.com/6ba231bb-ad9e-41b9-b23d-674c80196bbd/discovery/keys
              cacheDuration: 5m
          audiences:
            - "api://11ddc0cd-e6fc-48b6-8832-de61800fb41e"
